apiVersion: apps/v1
kind: Deployment
metadata:
  name: repsy-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repsy-docs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: repsy-docs
    spec:
      containers:
        - name: repsy-docs
          image: registry.gitlab.com/fria/repsy/repsy-cloud/repsy-docs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: repsy-docs
spec:
  selector:
    app: repsy-docs
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
