name: Build | Repsy Docs

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: build-docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: false

      - name: Set up Hugo and theme
        uses: ./.github/actions/setup-hugo-site

      - name: Build
        run: hugo --minify
