name: Repsy Docs CI

on:
  push:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  deploy-staging:
    environment: 'staging'
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install kubectl
        uses: Azure/setup-kubectl@v1

      - name: Build docker image
        env:
          DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: bash ./deploy.sh staging

  deploy-prod:
    environment: 'prod'
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install kubectl
        uses: Azure/setup-kubectl@v1

      - name: Build and deploy docker image
        env:
          DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: bash ./deploy.sh prod
