name: Repsy Docs CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    timeout-minutes: 5
    environment: prod
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Add DOCKER_IMAGE_TAG env property with commit short sha
        run: echo "DOCKER_IMAGE_TAG=`echo ${GITHUB_SHA::7}`" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: registry.gitlab.com/fria/repsy/repsy-cloud/repsy-docs:${{ env.DOCKER_IMAGE_TAG }},registry.gitlab.com/fria/repsy/repsy-cloud/repsy-docs:latest

      - name: Set Kubernetes Context
        uses: Azure/k8s-set-context@v3.0
        with:
          kubeconfig: ${{secrets.KUBE_CONFIG}}

      - name: Deploy
        uses: Azure/k8s-deploy@v4
        with:
          namespace: repsy-docs
          manifests: infrastructure/repsy-docs.yml
          images: registry.gitlab.com/fria/repsy/repsy-cloud/repsy-docs:${{ env.DOCKER_IMAGE_TAG }}
