name: Deploy Repsy Docs Dev to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_REPSY_DOCS_DEV_PROJECT_ID }}
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Install Hugo and Theme" ]
    types:
      - completed
  push:
    branches:
      - '*'
  pull_request:
    branches:
        - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: Download and Setup Hugo Theme
        run: |
          THEME_VERSION=2.5.0
          wget -q --no-check-certificate "https://github.com/matcornic/hugo-theme-learn/archive/${THEME_VERSION}.tar.gz"
          rm -rf themes/*
          mv "${THEME_VERSION}.tar.gz" themes/
          cd themes
          tar xzf "${THEME_VERSION}.tar.gz"
          mv "hugo-theme-learn-${THEME_VERSION}" hugo-theme-learn

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
